### PR TITLE
All Categories menu UI fixed

### LINKED ISSUE #2: "All categories" menu UI
The All Categories menu UI can be enhanced more and can be made to look professional.
image
The menu is touching the bottom of navbar, which can be fixed.

@bhavy3103 Please assign this issue to me under hacktoberfest.

Thanks

### PR DESCRIPTION
**Pull request by krishp007**
FIxes #2 

Before
image

After
image
image

Also, changed the navbar text color from black to white to make it consistent with Home page.

**Please add hacktoberfest label @bhavy3103** 

Thanks

### CODE REVIEW

**Comment by krishp007** [comment]
Please let me know if there is any issue with the code, I will fix it @bhavy3103

**Comment by bhavy3103** [comment]
> Please let me know if there is any issue with the code, I will fix it @bhavy3103

https://gist.github.com/szemate/6fb69c8e3d8cce3efa9a6c922b337d98
@krishp007 can you just refer above and do it again? I have ongoing my exams otherwise I will do it.

**Comment by krishp007** [comment]
Okay I will try, so after following the steps to resolve conflicts, do I have to make a PR again? @bhavy3103

**Comment by bhavy3103** [comment]
> Okay I will try, so after following the steps to resolve conflicts, do I have to make a PR again? @bhavy3103

No just push commit in same branch in which you are pushing right now . No need to make other pr, changes will reflect here automatically.

**Comment by krishp007** [comment]
I am getting this kind of error whenever i am executing `npm install` in frontend folder
image

Can you suggest how to fix this, because this is not the case with other modules(backend, socket).

**Comment by bhavy3103** [comment]
@krishp007 try yarn i

**Comment by bhavy3103** [comment]
your latest push in this pr affects the backend deployment it will crash if i merge this. So first pull the latest code and then do it and resolve conflicts.

**Pull request closed without merging**
