### PR TITLE
Fixes: #19: Navbar animation for dropdown and save, cart buttons

### LINKED ISSUE #19: [ENHANCEMENT] navbar animation for dropdown and save, cart buttons
clicking the navbar dropdown, show the dropdown items very abruptly without any animation, same is with save, cart button.

Hey @bhavy3103  Please assign this task to me so that I can start working on it.
If there is any preference from your side, please tell me.
And also don't forget to add Labels on this for **_Hactoberfest_**

### PR DESCRIPTION
**Pull request by ashish-um**
Fixes #19 
New much smoother animation have been implemented, utilizing tailwind features by adding animations in the ts config file :) 

https://github.com/user-attachments/assets/4bea471e-30bf-4e37-9948-eac280535186

### CODE REVIEW

**Review by bhavy3103 — COMMENTED** [review]
can you add on like wherever I click on my screen instead of dropdown then it will be closed if dropdown is open.

**Comment by ashish-um** [comment]
@bhavy3103 now the dropdown closes even on clicking outside it. I hope this fixes the issue :)

https://github.com/user-attachments/assets/ee010728-c7d6-4cc9-b8a2-d25c7b5b8c1d

**Comment by bhavy3103** [comment]
Everything was good and perfect just previous commit also raised this same issue but you have more features than it. Could please set some margin so it looks cool like this 
image

**Comment by ashish-um** [comment]
@bhavy3103 added the margin :+1:

**Pull request merged**
