### PR TITLE
Current year has been updated

### PR DESCRIPTION
**Pull request by anshgautam-github**
#52 fixed.

### CODE REVIEW

**Comment by bhavy3103** [comment]
push other related small tasks in this same PR.

**Comment by anshgautam-github** [comment]
u mean that spelling issues ?

**Comment by bhavy3103** [comment]
> u mean that spelling issues ?

yes and 3 issues you have raised in issue section

**Comment by anshgautam-github** [comment]
Okay sure

**Comment by anshgautam-github** [comment]
i am not sure how to add those issues in the same pr. like if again request a PR then will it automatically gets added in this? , or shall i close this pr and add all issues in the new pr all together

**Comment by bhavy3103** [comment]
> i am not sure how to add those issues in the same pr. like if I again creates a PR then will it automatically gets added in this? , or shall i close this pr and add all issues in the new pr all together

add changes in the same branch no need to close and then open it again.
just change all the things in one commit or you can do separate commit for particular change make sure all this are in same branch so it will be shown here as separate commit in one PR.

**Comment by anshgautam-github** [comment]
> > i am not sure how to add those issues in the same pr. like if I again creates a PR then will it automatically gets added in this? , or shall i close this pr and add all issues in the new pr all together
> 
> add changes in the same branch no need to close and then open it again. just change all the things in one commit or you can do a separate commit for a particular change make sure all these are in the same branch so it will be shown here as a separate commit in one PR.

Okay thank you

**Comment by anshgautam-github** [comment]
I have added the 2 spelling issues and 1 year change issue in this pr. One is remaining of the missing company logos, in which i am finding a little bit difficulty so till then can u merge all these 3 issues under hacktoberfest?

**Comment by bhavy3103** [comment]
> I have added the 2 spelling issues and 1 year change issue in this pr. One is remaining of the missing company logos, in which i am finding a little bit difficulty so till then can u merge all these 3 issues under hacktoberfest?

can you add the year dynamically based on date.now() then implement in next commit i will merge it.

**Comment by anshgautam-github** [comment]
> > I have added the 2 spelling issues and 1 year change issue in this pr. One is remaining of the missing company logos, in which i am finding a little bit difficulty so till then can u merge all these 3 issues under hacktoberfest?
> 
> can you add the year dynamically based on date.now() then implement in next commit i will merge it.

Sure

**Comment by anshgautam-github** [comment]
I have done that!

**Review by bhavy3103 — APPROVED** [review]
Done

**Pull request merged**
